name: CI

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          wget https://github.com/bazelbuild/bazel/releases/download/3.4.1/bazel_3.4.1-linux-x86_64.deb
          sudo dpkg -i bazel_3.4.1-linux-x86_64.deb
          sudo apt install lcov
          sudo apt install pkg-config

      - name: Build and Test
        run: |
          bazel build --config=328p --verbose_failures //:miniboot_hex | tee build_log.txt

      - name: Post summary to PR
        run: |
          POST_SUMMARY_TOKEN=${{ secrets.POST_SUMMARY_TOKEN }}
          ./scripts/post_summary.sh build_log.txt $POST_SUMMARY_TOKEN
